const ROUTE_DISPLAY_COUPONS = "/DisplayCoupons";
const ROUTE_USER_IDENTIFICATION = "/userIdentification";
const ROUTE_SCAN_IMAGE = "/ScanImage";
const ROUTE_HOME_PAGE = "/";
export {ROUTE_DISPLAY_COUPONS,ROUTE_HOME_PAGE,ROUTE_SCAN_IMAGE,ROUTE_USER_IDENTIFICATION};